units           real
atom_style      full
boundary        p p p
comm_style      brick
# newton off                           
special_bonds   lj/coul 0.0 0.0 1.0
bond_style      class2
angle_style     class2
dihedral_style  class2
improper_style  class2
pair_style      soft 10.0
read_data       setup.data
include         setup.params
pair_modify     tail no
variable        ZHALF   equal 40.0     # половина целевой толщины плёнки, A
variable        ZBOX    equal 240.0    # полувысота ячейки (вакуум), A
variable        NZBOX   equal "-v_ZBOX"
variable        NZHALF  equal "-v_ZHALF"
variable        SOFTCUT equal 3.0
variable        SOFTA   equal 60.0
variable        NPUSH   equal 150000
variable        NHOLD   equal 50000

neighbor        2.0 bin
neigh_modify    delay 0 every 1 check yes

pair_style      soft $(v_SOFTCUT)
comm_modify     cutoff 8.0
pair_coeff      * * $(v_SOFTA)
dump            TRJ all custom 10000 dump.soft.lammpstrj.gz id mol type q x y z
min_modify dmax 0.1
min_style cg
minimize 1.0e-4 1.0e-5 5000 50000
min_style cg
minimize 1.0e-8 1.0e-10 20000 200000

timestep        0.1
fix             1 all nve/limit 0.05
fix             2 all viscous 50.0
fix             3 all dt/reset 1 NULL 0.001 0.1
thermo          1000
run             10000
# fix_modify      1 energy yes
unfix           1
unfix           2
unfix           3

velocity        all zero linear
velocity        all zero angular

compute         ZMIN all reduce min z
compute         ZMAX all reduce max z
thermo_style    custom step temp press lz pe atoms c_ZMIN c_ZMAX
run             0 post no
variable        DZSHIFT equal "-(c_ZMIN+c_ZMAX)/2.0"
displace_atoms  all move 0.0 0.0 $(v_DZSHIFT) units box

change_box      all boundary p p f
run             0 post no

variable        ZB0 equal "c_ZMIN-5.0"
variable        ZT0 equal "c_ZMAX+5.0"
variable        ZB0F internal $(v_ZB0)
variable        ZT0F internal $(v_ZT0)
variable        z_bot equal "ramp(v_ZB0F,v_NZHALF)"
variable        z_top equal "ramp(v_ZT0F,v_ZHALF)"

fix             wall_b all wall/reflect zlo v_z_bot units box
fix             wall_t all wall/reflect zhi v_z_top units box

fix             1 all langevin 300.0 300.0 100.0 48279
fix             2 all nve

variable        film_dens equal "mass(all)/(0.6022141*lx*ly*(2.0*v_ZHALF))"

thermo          2000
thermo_style    custom step temp press lz pe atoms c_ZMIN c_ZMAX v_film_dens
timestep	0.5
run             ${NPUSH}

unfix           wall_b
unfix           wall_t
fix             final_wall_b all wall/reflect zlo v_NZHALF units box
fix             final_wall_t all wall/reflect zhi v_ZHALF  units box

velocity        all scale 300.0
run             ${NHOLD}
timestep	0.5
include         setup.params
pair_modify     tail no
kspace_style pppm 1.0e-4
kspace_modify   slab 3.0
neighbor        2.0 bin
neigh_modify    delay 0 every 1 check yes

unfix           1
unfix           2

change_box all z final -50 50
write_data      Polymer_G42.data
